myproject/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learningapp.urls')),
    
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learningapp/models.py
from django.db import models
from django.contrib.auth.models import User

from autoslug import AutoSlugField


# Create your models here.

class PhoneNumber(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15)




class Course(models.Model):
    course_name = models.CharField(max_length=250, unique=True)
    slug = AutoSlugField(populate_from='course_name', unique=True, null=True)
    course_price = models.CharField(max_length=10, default=None)
    course_offer_price = models.CharField(max_length=10, default=None)
    course_description = models.TextField()
    course_type = models.CharField(max_length=10, choices=[('paid', 'Paid'), ('free', 'Free')])  # True for Paid, False for Unpaid
    course_status = models.CharField(max_length=10, choices=[('active', 'Active'), ('inactive', 'Inactive')])
    thumbnail = models.ImageField(
        upload_to='course_thumbnails',
        blank=True,
        null=True, 
        default='course/default.png'
    )
    
    create_at = models.DateField(null=True, blank=True, auto_now=True)
    update_at = models.DateField(null=True, blank=True, auto_now=True)
    delete_at = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.course_name}"
    










class Quiz(models.Model):
        course = models.ForeignKey(Course, on_delete=models.CASCADE)
        quiz_title = models.CharField(max_length=50)
        description = models.TextField()
        time_limit = models.IntegerField()
        randomize_questions = models.BooleanField(default=False)
        attempts_allowed = models.IntegerField()

        def __str__(self):
            return self.quiz_title
        






class QuizQuestion(models.Model):
        QUIZ_QUESTION_TYPES = (
            ('multiple_choice', 'Multiple Choice'),
            ('true_false', 'True/False'),
            ('short_answer', 'Short Answer'),
        )

        quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
        question_text = models.TextField()
        question_type = models.CharField(max_length=20, choices=QUIZ_QUESTION_TYPES)
        points = models.IntegerField()

        def __str__(self):
            return self.question_text  
          
class QuizChoice(models.Model):
    question = models.ForeignKey(QuizQuestion, related_name='choices', on_delete=models.CASCADE)
    choice_text = models.TextField()
    is_correct = models.BooleanField()

    def __str__(self):
            return self.choice_text 
    












    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>eLEARNING - eLearning HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'images/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css'  %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    


    {% include 'nav.html'%}
    {% block content%}

    {% endblock %}
    {% include 'footer.html' %}




    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>




   



   
 
</body>

</html>

templates/course_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}



<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Course Details</title>
</head>

<body>
    <div class="container">
        <h1 class="main_head">{{ course.course_name }}</h1>
        <div class="row">
            <div class="col-md-6">
                <img src="{{ course.thumbnail.url }}" alt="Course Thumbnail">
            </div>
            <div class="col-md-6">
                <p>Description: {{ course.course_description }}</p>
                <p>Price: {{ course.course_price }}</p>
                <p>Offer Price: {{ course.course_offer_price }}</p>
                <p>Type: {{ course.course_type }}</p>
                <p>Status: {{ course.course_status }}</p>

                <p>
                    "Welcome to our quiz section, where you can test your knowledge on a wide range of computer courses
                    and technologies! Whether you're interested in programming languages, web development,
                    cybersecurity, or emerging technologies like artificial intelligence and blockchain, we've got you
                    covered. Our quizzes are designed to challenge and educate, providing valuable insights into the
                    ever-evolving world of technology. So, gear up, select your area of interest, and let's dive into
                    the fascinating realm of computer science together!"
                </p>




                <!-- <form method="post" action="{% url 'submit_quiz' %}">
                    {% csrf_token %}
                    {% for quiz in quizzes %}
                        <h2>{{ quiz.quiz_title }}</h2>
                        <ol>
                            {% for question in quiz.quizquestion_set.all %}
                                <li>{{ question.question_text }}</li>
                                <ul>
                                    {% for choice in question.choices.all %}
                                        <li><input type="radio" name="question{{ question.id }}" value="{{ choice.id }}"> {{ choice.choice_text }}</li>
                                    {% endfor %}
                                </ul>
                            {% endfor %}
                        </ol>
                    {% endfor %}
                    <button type="submit">Submit</button>
                </form>
                 -->

                 {% for quiz in quizzes %}
                 <h2>{{ quiz.quiz_title }}</h2>
                 <form method="post" action="">
                     {% csrf_token %}
                     <ol>
                         {% for question in quiz.quizquestion_set.all %}
                             <li>{{ question.question_text }}</li>
                             <ul>
                                 {% for choice in question.choices.all %}
                                     <li><input type="radio" name="question{{ question.id }}" value="{{ choice.id }}"> {{ choice.choice_text }}</li>
                                 {% endfor %}
                             </ul>
                         {% endfor %}
                     </ol>
                    
                     <button type="submit" class="btn btn-info">Submit</button>
                 </form>
             {% endfor %}
         
             {% if total_score is not None %}
                 <p>Your total score is: {{ total_score }}</p>
             {% endif %}


                
            </div>
        </div>
    </div>
</body>

</html>

{% endblock%}

templates/delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete</title>
    <link rel="stylesheet" href="{% static './css1/style.css' %} ">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>



</head>
<body>
    
    
</body>
</html>

templates/footer.html
{% load static %}
{% block content %}
 <!-- Footer Start -->
 <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Quick Link</h4>
                <a class="btn btn-link" href="">About Us</a>
                <a class="btn btn-link" href="">Contact Us</a>
                <a class="btn btn-link" href="">Privacy Policy</a>
                <a class="btn btn-link" href="">Terms & Condition</a>
                <a class="btn btn-link" href="">FAQs & Help</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Contact</h4>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Gallery</h4>
                <div class="row g-2 pt-2">
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'images/course-1.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'images/course-2.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'images/course-3.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'images/course-2.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'images/course-3.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid bg-light p-1" src="{% static 'images/course-1.jpg' %}" alt="">
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-white mb-3">Newsletter</h4>
                <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                <div class="position-relative mx-auto" style="max-width: 400px;">
                    <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                    <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a><br><br>
                    Distributed By <a class="border-bottom" href="https://themewagon.com">ThemeWagon</a>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a href="">Home</a>
                        <a href="">Cookies</a>
                        <a href="">Help</a>
                        <a href="">FQAs</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->
{% endblock %}

templates/login.html
{% load static %}

<html>
    <head>
    
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    </head>
 
<body class="grad2" >
<div class="d-flex justify-content-center align-items-center p-5 m-5">
     <div class=" card p-5" >
          <form method="post">
        <h2 class="text-center pb-5">LOGIN</h2>

        {% csrf_token %}
        {{ form.as_p }}

        <button  class="btn btn-info">LOGIN</button>
        <a href="{% url 'signup' %}">SIGNUP</a>
       
      </form>
    </div>
  
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>    
</body>
</html>
  

templates/nav.html
 {% block content %}
 <!-- Navbar Start  -->
 <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="index.html" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>eLEARNING</h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="index.html" class="nav-item nav-link active">Home</a>
            <a href="about.html" class="nav-item nav-link">About</a>
            <!-- <a href="courses.html" class="nav-item nav-link">Courses</a> -->

            <a href="{% url 'course_fullview' %}" class="nav-item nav-link">Courses</a>

            <a href="contact.html" class="nav-item nav-link">Contact</a>

           
            {% if user.is_authenticated %}
            <span class="nav-item nav-link">Welcome {{ user.username }}</span>
            {% else %}
            <a href="{% url 'contact' %}" class="nav-item nav-link">Contact</a>
            {% endif %}



        </div>
        <a href="{% url 'signup'%}" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Join Now<i class="fa fa-arrow-right ms-3"></i></a>
    </div>


</nav>
 <!-- Navbar End  -->
 {% endblock %} 

templates/signup.html
{% load static %}
<html>
    <head>
         <link rel="stylesheet" href="../static/css/styles1.css">
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    </head>
    
    
<body class="grad2">
    <div style='display: flex; justify-content: center; height: 100vh; align-items: center;' >
      <div class="card p-5" style=" color: rgb(9, 12, 15); background-color: rgb(33, 191, 191) !important;">
         <h1 style="text-align: center;">SIGNUP</h1>
        <form method="post">
            {% csrf_token %}
            <table style="color: rgb(12, 12, 12);">
                <tr>
                    <td>Username</td>
                    <td>{{form.username}}</td>
        
        
                </tr>
                <tr>
                    <td>Email</td>
                    <td>{{form.email}}</td>
                </tr>
                <tr>
                    <td>Firstname</td>
                    <td>{{form.first_name}}</td>
                </tr>
                <tr>
                    <td>lastname</td>
                    <td>{{form.last_name}}</td>
                </tr>
                <tr>
                    <td>Password1</td>
                    <td>{{form.password1}}</td>
                </tr>
                <tr>
                    <td>Password2</td>
                    <td>{{form.password2}}</td>
                </tr>
                <tr>
                    <td>Phonenumber</td>
                    <td>{{form.phone_number}}</td>
                </tr>

            </table>
            <button type="submit" class="btn btn-success d-block m-auto mt-4" >SUBMIT</button>
           
        </form>
        <p class="mt-3 text-center">Already have an account? <a href="{% url 'login' %}">Go to Login</a></p>

      </div>
       
    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
       
    
        

    </div>

    
    
</body>
</html>